version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./user-service/sql/init.sql:/docker-entrypoint-initdb.d/01-init-user.sql
      - ./salle-service/sql/init.sql:/docker-entrypoint-initdb.d/02-init-salle.sql
      - ./reservation-service/sql/init.sql:/docker-entrypoint-initdb.d/03-init-reservation.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DB_HOST: mysql
      KAFKA_BROKER: kafka:9092
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CALLBACK_URL: ${CALLBACK_URL}

  salle-service:
    build: ./salle-service
    container_name: salle-service
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DB_HOST: mysql
      KAFKA_BROKER: kafka:9092
  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    ports:
      - "3003:3003"  # Change le port ici si nécessaire
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DB_HOST: mysql
      KAFKA_BROKER: kafka:9092

volumes:
  mysql_data: