# Projet SonarQube
sonar.projectKey=nodejs-project
sonar.projectName=Node.js Project
sonar.projectVersion=1.0

# Les sources à analyser
sonar.sources=src

# Le langage utilisé
sonar.language=js

# Configuration des tests (si vous en avez)
sonar.tests=tests

# Le chemin vers le rapport de couverture de tests (si applicable)
sonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov-report.json

# Authentification SonarQube (si vous utilisez un token d'authentification)
sonar.login=your_sonarqube_token
